version: "3"
services:
  app:
    container_name: fastapi-mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./.env:/app/.env
    working_dir: /app
    command: python main.py
    network_mode: host
